### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by jitchavan** [zalando/oauth2-client-js#30]
we are getting window is not defined error as below. 

`ReferenceError: window is not defined at new Provider (webpack:///./src/provider.js?:42:86) at Object.<anonymous> (/home/Demo-App/demo/tmp/webpack:/src/routes/requireAuthentication.js:10:20) at webpack_require (/home/Demo-App/demo/tmp/webpack:/webpack/bootstrap 4f5669005e928a572010:19:1) at Object.exports.__esModule (/home/Demo-App/demo/tmp/webpack:/src/routes.js:15:1) at webpack_require (/home/Demo-App/demo/tmp/webpack:/webpack/bootstrap 4f5669005e928a572010:19:1) at Object.<anonymous> (/home/Demo-App/demo/tmp/webpack:/server.babel.js:9:1) at webpack_require (/home/Demo-App/demo/tmp/webpack:/webpack/bootstrap 4f5669005e928a572010:19:1) at Object.<anonymous> (/home/Demo-App/demo/tmp/bundle.js:50:19) at webpack_require (/home/Demo-App/demo/tmp/webpack:/webpack/bootstrap 4f5669005e928a572010:19:1) at /home/Demo-App/demo/tmp/webpack:/webpack/bootstrap 4f5669005e928a572010:39:1 `

I receive a window is not defined error at 
```
var provider = new OAuth.Provider({ 
id: 'google', // required 
authorization_url: 'https://google.com/auth' // required
 }); 

```
our package json versions are as below. 
```
"oauth2-client-js": "0.0.15", 
"react": "^15.4.0", 
"react-dom": "^15.4.0"
```

**Comment by jgauntz** [comment]
Was this ever resolved?
